---
# 全局变量配置
# 这里的变量会应用到所有主机

# Curvine安装配置
curvine_install_dir: /root/dist
curvine_config_file: "{{ curvine_install_dir }}/conf/curvine-cluster.toml"

# 安装包路径（控制节点上的路径）
master_dist_file: /root/dist.tar.gz
worker_dist_file: /root/dist1.tar.gz

# 数据目录配置（可以在这里修改，部署时会使用这些配置）
data_dirs:
  - "[SSD]/data/data"
  # 添加更多数据目录示例：
  # - "[SSD]/data/data1"
  # - "[SSD]/data/data2"
  # - "[HDD]/data/data3"

# SSH配置
ansible_user: root
ansible_port: 22

# 服务配置
curvine_services_master:
  - curvine-master
  - curvine-worker
  - curvine-fuse

curvine_services_worker:
  - curvine-worker
  - curvine-fuse

