---
# 密码配置示例文件
# 如果不同节点使用不同密码，可以复制此文件为 passwords.yml 并填写实际密码
# 然后使用: ansible-playbook setup_ssh.yml -e @passwords.yml

# 方式1: 为整个主机组设置密码
master_password: "your_master_password_here"
worker_password: "your_worker_password_here"

# 方式2: 为特定主机设置密码（在hosts.ini中使用）
# [master]
# 192.168.1.10 ansible_password=password1
# 192.168.1.11 ansible_password=password2
# 
# [worker]
# 192.168.1.20 ansible_password=password3
# 192.168.1.21 ansible_password=password4

