apiVersion: v2
name: curvine-csi
description: A Helm chart for Curvine CSI Driver
type: application
version: 0.0.0-latest
appVersion: "latest"
keywords:
  - storage
  - csi
  - curvine
home: https://github.com/CurvineIO/curvine
sources:
  - https://github.com/CurvineIO/curvine
maintainers:
  - name: Curvine Team
    email: curvine86@gmail.com
    url: https://github.com/curvineio
